// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: namespacepb/namespace.proto

package namespacepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceRequest) Reset() {
	*x = CreateNamespaceRequest{}
	mi := &file_namespacepb_namespace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceRequest) ProtoMessage() {}

func (x *CreateNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_namespacepb_namespace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceRequest.ProtoReflect.Descriptor instead.
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_namespacepb_namespace_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNamespaceRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateNamespaceRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceResponse) Reset() {
	*x = CreateNamespaceResponse{}
	mi := &file_namespacepb_namespace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceResponse) ProtoMessage() {}

func (x *CreateNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_namespacepb_namespace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceResponse.ProtoReflect.Descriptor instead.
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_namespacepb_namespace_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNamespaceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_namespacepb_namespace_proto protoreflect.FileDescriptor

const file_namespacepb_namespace_proto_rawDesc = "" +
	"\n" +
	"\x1bnamespacepb/namespace.proto\x12\tnamespace\"E\n" +
	"\x16CreateNamespaceRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\"1\n" +
	"\x17CreateNamespaceResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2l\n" +
	"\x10NamespaceService\x12X\n" +
	"\x0fCreateNamespace\x12!.namespace.CreateNamespaceRequest\x1a\".namespace.CreateNamespaceResponseB\x1fZ\x1dproto/namespacepb;namespacepbb\x06proto3"

var (
	file_namespacepb_namespace_proto_rawDescOnce sync.Once
	file_namespacepb_namespace_proto_rawDescData []byte
)

func file_namespacepb_namespace_proto_rawDescGZIP() []byte {
	file_namespacepb_namespace_proto_rawDescOnce.Do(func() {
		file_namespacepb_namespace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_namespacepb_namespace_proto_rawDesc), len(file_namespacepb_namespace_proto_rawDesc)))
	})
	return file_namespacepb_namespace_proto_rawDescData
}

var file_namespacepb_namespace_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_namespacepb_namespace_proto_goTypes = []any{
	(*CreateNamespaceRequest)(nil),  // 0: namespace.CreateNamespaceRequest
	(*CreateNamespaceResponse)(nil), // 1: namespace.CreateNamespaceResponse
}
var file_namespacepb_namespace_proto_depIdxs = []int32{
	0, // 0: namespace.NamespaceService.CreateNamespace:input_type -> namespace.CreateNamespaceRequest
	1, // 1: namespace.NamespaceService.CreateNamespace:output_type -> namespace.CreateNamespaceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_namespacepb_namespace_proto_init() }
func file_namespacepb_namespace_proto_init() {
	if File_namespacepb_namespace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_namespacepb_namespace_proto_rawDesc), len(file_namespacepb_namespace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_namespacepb_namespace_proto_goTypes,
		DependencyIndexes: file_namespacepb_namespace_proto_depIdxs,
		MessageInfos:      file_namespacepb_namespace_proto_msgTypes,
	}.Build()
	File_namespacepb_namespace_proto = out.File
	file_namespacepb_namespace_proto_goTypes = nil
	file_namespacepb_namespace_proto_depIdxs = nil
}
