// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: userpb/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnsureUserExistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KID           string                 `protobuf:"bytes,1,opt,name=KID,proto3" json:"KID,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureUserExistRequest) Reset() {
	*x = EnsureUserExistRequest{}
	mi := &file_userpb_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureUserExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureUserExistRequest) ProtoMessage() {}

func (x *EnsureUserExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureUserExistRequest.ProtoReflect.Descriptor instead.
func (*EnsureUserExistRequest) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{0}
}

func (x *EnsureUserExistRequest) GetKID() string {
	if x != nil {
		return x.KID
	}
	return ""
}

func (x *EnsureUserExistRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type EnsureUserExistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureUserExistResponse) Reset() {
	*x = EnsureUserExistResponse{}
	mi := &file_userpb_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureUserExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureUserExistResponse) ProtoMessage() {}

func (x *EnsureUserExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureUserExistResponse.ProtoReflect.Descriptor instead.
func (*EnsureUserExistResponse) Descriptor() ([]byte, []int) {
	return file_userpb_user_proto_rawDescGZIP(), []int{1}
}

func (x *EnsureUserExistResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_userpb_user_proto protoreflect.FileDescriptor

const file_userpb_user_proto_rawDesc = "" +
	"\n" +
	"\x11userpb/user.proto\x12\x04user\"@\n" +
	"\x16EnsureUserExistRequest\x12\x10\n" +
	"\x03KID\x18\x01 \x01(\tR\x03KID\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"2\n" +
	"\x17EnsureUserExistResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2]\n" +
	"\vUserService\x12N\n" +
	"\x0fEnsureUserExist\x12\x1c.user.EnsureUserExistRequest\x1a\x1d.user.EnsureUserExistResponseB\x15Z\x13proto/userpb;userpbb\x06proto3"

var (
	file_userpb_user_proto_rawDescOnce sync.Once
	file_userpb_user_proto_rawDescData []byte
)

func file_userpb_user_proto_rawDescGZIP() []byte {
	file_userpb_user_proto_rawDescOnce.Do(func() {
		file_userpb_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userpb_user_proto_rawDesc), len(file_userpb_user_proto_rawDesc)))
	})
	return file_userpb_user_proto_rawDescData
}

var file_userpb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_userpb_user_proto_goTypes = []any{
	(*EnsureUserExistRequest)(nil),  // 0: user.EnsureUserExistRequest
	(*EnsureUserExistResponse)(nil), // 1: user.EnsureUserExistResponse
}
var file_userpb_user_proto_depIdxs = []int32{
	0, // 0: user.UserService.EnsureUserExist:input_type -> user.EnsureUserExistRequest
	1, // 1: user.UserService.EnsureUserExist:output_type -> user.EnsureUserExistResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userpb_user_proto_init() }
func file_userpb_user_proto_init() {
	if File_userpb_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userpb_user_proto_rawDesc), len(file_userpb_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userpb_user_proto_goTypes,
		DependencyIndexes: file_userpb_user_proto_depIdxs,
		MessageInfos:      file_userpb_user_proto_msgTypes,
	}.Build()
	File_userpb_user_proto = out.File
	file_userpb_user_proto_goTypes = nil
	file_userpb_user_proto_depIdxs = nil
}
